// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DiskSnapshotInitParameters struct {

	// Arbitrary information about this snapshot provided by user.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	Metadata *DiskSnapshotMetadataInitParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// Identifier of the source disk. May become stale if the disk is deleted.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/cluster/compute/v1beta1.Disk
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	SourceDiskID *string `json:"sourceDiskId,omitempty" tf:"source_disk_id,omitempty"`

	// Reference to a Disk in compute to populate sourceDiskId.
	// +kubebuilder:validation:Optional
	SourceDiskIDRef *v2.Reference `json:"sourceDiskIdRef,omitempty" tf:"-"`

	// Selector for a Disk in compute to populate sourceDiskId.
	// +kubebuilder:validation:Optional
	SourceDiskIDSelector *v2.Selector `json:"sourceDiskIdSelector,omitempty" tf:"-"`
}

type DiskSnapshotMetadataInitParameters struct {
}

type DiskSnapshotMetadataObservation struct {
}

type DiskSnapshotMetadataParameters struct {
}

type DiskSnapshotObservation struct {

	// :
	//
	// Timestamp indicating when the resource was created.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Arbitrary information about this snapshot provided by user.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Effective labels sent to the API after merging provider `default_labels` with resource `labels`.
	// +mapType=granular
	LabelsAll map[string]*string `json:"labelsAll,omitempty" tf:"labels_all,omitempty"`

	Metadata *DiskSnapshotMetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// :
	//
	// Version of the resource for safe concurrent modifications and consistent reads.
	// Positive and monotonically increases on each resource spec change (but *not* on each change of the
	// resource's container(s) or status).
	// Service allows zero value or current.
	ResourceVersion *float64 `json:"resourceVersion,omitempty" tf:"resource_version,omitempty"`

	// Identifier of the source disk. May become stale if the disk is deleted.
	SourceDiskID *string `json:"sourceDiskId,omitempty" tf:"source_disk_id,omitempty"`

	Status *DiskSnapshotStatusObservation `json:"status,omitempty" tf:"status,omitempty"`

	// :
	//
	// Timestamp indicating when the resource was last updated.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type DiskSnapshotParameters struct {

	// Arbitrary information about this snapshot provided by user.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Labels associated with the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// +kubebuilder:validation:Optional
	Metadata *DiskSnapshotMetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	// +kubebuilder:validation:Optional
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// Identifier of the source disk. May become stale if the disk is deleted.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/cluster/compute/v1beta1.Disk
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	// +kubebuilder:validation:Optional
	SourceDiskID *string `json:"sourceDiskId,omitempty" tf:"source_disk_id,omitempty"`

	// Reference to a Disk in compute to populate sourceDiskId.
	// +kubebuilder:validation:Optional
	SourceDiskIDRef *v2.Reference `json:"sourceDiskIdRef,omitempty" tf:"-"`

	// Selector for a Disk in compute to populate sourceDiskId.
	// +kubebuilder:validation:Optional
	SourceDiskIDSelector *v2.Selector `json:"sourceDiskIdSelector,omitempty" tf:"-"`
}

type DiskSnapshotStatusInitParameters struct {
}

type DiskSnapshotStatusObservation struct {

	// :
	//
	// Logical size of the snapshot content.
	// This is the size of a disk that would be created from this snapshot.
	ContentSizeBytes *float64 `json:"contentSizeBytes,omitempty" tf:"content_size_bytes,omitempty"`

	LockState *StatusLockStateObservation `json:"lockState,omitempty" tf:"lock_state,omitempty"`

	// :
	//
	// CPU architecture associated with the source disk.
	// Not set if the architecture is unknown.
	//
	// #### Supported values
	//
	// Right now UNDEFINED is an alias for AMD64, but that might change in the future
	// Possible values:
	//
	// - `UNDEFINED`
	// - `AMD64`
	// - `ARM64`
	SourceCPUArchitecture *string `json:"sourceCpuArchitecture,omitempty" tf:"source_cpu_architecture,omitempty"`

	// :
	//
	// #### Supported values
	//
	// All possible states for DiskSnapshot resource
	// Possible values:
	//
	// - `UNSPECIFIED`
	// - `CREATING`
	// - `READY`
	// - `DELETING`
	// - `ERROR`
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// :
	//
	// Physical storage used by this snapshot in the snapshot backend.
	// This value is used for billing and quota and may change over time as the snapshot chain evolves
	// (e.g., when earlier snapshots are deleted and data gets re-attributed).
	// Currently is equal to content_size_bytes, as incremental snapshots are not supported yet.
	StorageSizeBytes *float64 `json:"storageSizeBytes,omitempty" tf:"storage_size_bytes,omitempty"`
}

type DiskSnapshotStatusParameters struct {
}

type StatusLockStateInitParameters struct {
}

type StatusLockStateObservation struct {

	// :
	//
	// The snapshot is locked for deletion while disk is being created from this snapshot.
	// Here is the list of these disks.
	Disks []*string `json:"disks,omitempty" tf:"disks,omitempty"`
}

type StatusLockStateParameters struct {
}

// DiskSnapshotSpec defines the desired state of DiskSnapshot
type DiskSnapshotSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   DiskSnapshotParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DiskSnapshotInitParameters `json:"initProvider,omitempty"`
}

// DiskSnapshotStatus defines the observed state of DiskSnapshot.
type DiskSnapshotStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               DiskSnapshotObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DiskSnapshot is the Schema for the DiskSnapshots API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nebius}
type DiskSnapshot struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DiskSnapshotSpec   `json:"spec"`
	Status            DiskSnapshotStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DiskSnapshotList contains a list of DiskSnapshots
type DiskSnapshotList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DiskSnapshot `json:"items"`
}

// Repository type metadata.
var (
	DiskSnapshot_Kind             = "DiskSnapshot"
	DiskSnapshot_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DiskSnapshot_Kind}.String()
	DiskSnapshot_KindAPIVersion   = DiskSnapshot_Kind + "." + CRDGroupVersion.String()
	DiskSnapshot_GroupVersionKind = CRDGroupVersion.WithKind(DiskSnapshot_Kind)
)

func init() {
	SchemeBuilder.Register(&DiskSnapshot{}, &DiskSnapshotList{})
}
