// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type CapacityAllowanceInitParameters struct {

	// Capacity Block Group NID.
	CapacityBlockGroupID *string `json:"capacityBlockGroupId,omitempty" tf:"capacity_block_group_id,omitempty"`

	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// :
	//
	// Total amount of resources allocated.
	// Optional is used to define an unlimited Capacity Allowance.
	Limit *float64 `json:"limit,omitempty" tf:"limit,omitempty"`

	Metadata *MetadataInitParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`
}

type CapacityAllowanceObservation struct {

	// Capacity Block Group NID.
	CapacityBlockGroupID *string `json:"capacityBlockGroupId,omitempty" tf:"capacity_block_group_id,omitempty"`

	// :
	//
	// Timestamp indicating when the resource was created.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Effective labels sent to the API after merging provider `default_labels` with resource `labels`.
	// +mapType=granular
	LabelsAll map[string]*string `json:"labelsAll,omitempty" tf:"labels_all,omitempty"`

	// :
	//
	// Total amount of resources allocated.
	// Optional is used to define an unlimited Capacity Allowance.
	Limit *float64 `json:"limit,omitempty" tf:"limit,omitempty"`

	Metadata *MetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// :
	//
	// Version of the resource for safe concurrent modifications and consistent reads.
	// Positive and monotonically increases on each resource spec change (but *not* on each change of the
	// resource's container(s) or status).
	// Service allows zero value or current.
	ResourceVersion *float64 `json:"resourceVersion,omitempty" tf:"resource_version,omitempty"`

	Status *StatusObservation `json:"status,omitempty" tf:"status,omitempty"`

	// :
	//
	// Timestamp indicating when the resource was last updated.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type CapacityAllowanceParameters struct {

	// Capacity Block Group NID.
	// +kubebuilder:validation:Optional
	CapacityBlockGroupID *string `json:"capacityBlockGroupId,omitempty" tf:"capacity_block_group_id,omitempty"`

	// Labels associated with the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// :
	//
	// Total amount of resources allocated.
	// Optional is used to define an unlimited Capacity Allowance.
	// +kubebuilder:validation:Optional
	Limit *float64 `json:"limit,omitempty" tf:"limit,omitempty"`

	// +kubebuilder:validation:Optional
	Metadata *MetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	// +kubebuilder:validation:Optional
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`
}

type MetadataInitParameters struct {
}

type MetadataObservation struct {
}

type MetadataParameters struct {
}

type StatusInitParameters struct {
}

type StatusObservation struct {

	// Shows that changes are in flight.
	Reconciling *bool `json:"reconciling,omitempty" tf:"reconciling,omitempty"`

	// :
	//
	// Current state of the capacity allowance.
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `STATE_UNSPECIFIED`
	// - `STATE_PROVISIONING` - Capacity Allowance is being allocated; the process can take up to several minutes.
	// - `STATE_ACTIVE` - Capacity Allowance is allocated and can be used.
	// - `STATE_CONTAINER_DELETED` - The container of the Capacity Allowance is deleted. Capacity Allowance cannot be changed.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// :
	//
	// Capacity Allowance unit.
	// Example: "GPU".
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Current capacity allowance usage.
	Usage *float64 `json:"usage,omitempty" tf:"usage,omitempty"`

	// Capacity allowance usage percentage.
	UsagePercentage *string `json:"usagePercentage,omitempty" tf:"usage_percentage,omitempty"`

	// :
	//
	// Current state of the capacity allowance usage.
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `USAGE_STATE_UNSPECIFIED`
	// - `USAGE_STATE_USED` - Capacity allowance is actively in use.
	// - `USAGE_STATE_NOT_USED` - Capacity allowance is not currently in use.
	// - `USAGE_STATE_UNKNOWN`:
	// Capacity allowance region is unreachable, the current usage is therefore unknown.
	// Please, retry the request later.
	UsageState *string `json:"usageState,omitempty" tf:"usage_state,omitempty"`
}

type StatusParameters struct {
}

// CapacityAllowanceSpec defines the desired state of CapacityAllowance
type CapacityAllowanceSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   CapacityAllowanceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CapacityAllowanceInitParameters `json:"initProvider,omitempty"`
}

// CapacityAllowanceStatus defines the observed state of CapacityAllowance.
type CapacityAllowanceStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               CapacityAllowanceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CapacityAllowance is the Schema for the CapacityAllowances API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nebius}
type CapacityAllowance struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.capacityBlockGroupId) || (has(self.initProvider) && has(self.initProvider.capacityBlockGroupId))",message="spec.forProvider.capacityBlockGroupId is a required parameter"
	Spec   CapacityAllowanceSpec   `json:"spec"`
	Status CapacityAllowanceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CapacityAllowanceList contains a list of CapacityAllowances
type CapacityAllowanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CapacityAllowance `json:"items"`
}

// Repository type metadata.
var (
	CapacityAllowance_Kind             = "CapacityAllowance"
	CapacityAllowance_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CapacityAllowance_Kind}.String()
	CapacityAllowance_KindAPIVersion   = CapacityAllowance_Kind + "." + CRDGroupVersion.String()
	CapacityAllowance_GroupVersionKind = CRDGroupVersion.WithKind(CapacityAllowance_Kind)
)

func init() {
	SchemeBuilder.Register(&CapacityAllowance{}, &CapacityAllowanceList{})
}
