// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type InventoryInitParameters struct {

	// ID of the destination bucket.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/namespaced/storage/v1beta1.Bucket
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	DestinationBucketID *string `json:"destinationBucketId,omitempty" tf:"destination_bucket_id,omitempty"`

	// Reference to a Bucket in storage to populate destinationBucketId.
	// +kubebuilder:validation:Optional
	DestinationBucketIDRef *v2.NamespacedReference `json:"destinationBucketIdRef,omitempty" tf:"-"`

	// Selector for a Bucket in storage to populate destinationBucketId.
	// +kubebuilder:validation:Optional
	DestinationBucketIDSelector *v2.NamespacedSelector `json:"destinationBucketIdSelector,omitempty" tf:"-"`

	// Prefix under which bucket inventory will be stored in the destination bucket.
	DestinationPrefix *string `json:"destinationPrefix,omitempty" tf:"destination_prefix,omitempty"`

	// Enable or disable inventory generation.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	Metadata *InventoryMetadataInitParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Include noncurrent versions in inventory if set to true.
	NoncurrentVersions *bool `json:"noncurrentVersions,omitempty" tf:"noncurrent_versions,omitempty"`

	// :
	//
	// Optional fields to include in inventory.
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `OPTIONAL_FIELD_UNSPECIFIED`
	// - `LAST_ACCESS` - Timestamp of the last access.
	// - `CHECKSUM_ALGORITHMS` - Checksum algorithms used.
	// - `INTELLIGENT_TIER` - Current intelligent tier (for Intelligent Storage Class).
	// - `IS_MULTIPART_UPLOAD` - True for multipart uploads, false for simple objects.
	// - `LIFECYCLE_EXPIRATION` - Timestamp of lifecycle expiration.
	// - `TAGS` - Object tags.
	OptionalFields []*string `json:"optionalFields,omitempty" tf:"optional_fields,omitempty"`

	// :
	//
	// Inventory format.
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `OUTPUT_FORMAT_UNSPECIFIED`
	// - `CSV_GZIP` - CSV compressed with GZIP.
	// - `PARQUET_SNAPPY` - Parquet compressed with Snappy.
	OutputFormat *string `json:"outputFormat,omitempty" tf:"output_format,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/namespaced/storage/v1beta1.Bucket
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// Reference to a Bucket in storage to populate parentId.
	// +kubebuilder:validation:Optional
	ParentIDRef *v2.NamespacedReference `json:"parentIdRef,omitempty" tf:"-"`

	// Selector for a Bucket in storage to populate parentId.
	// +kubebuilder:validation:Optional
	ParentIDSelector *v2.NamespacedSelector `json:"parentIdSelector,omitempty" tf:"-"`

	// :
	//
	// How often to generate the inventory.
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `SCHEDULE_UNSPECIFIED`
	// - `DAILY` - Run once a day.
	// - `WEEKLY` - Run once a week.
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`

	// Prefix to filter objects in the source bucket.
	SourcePrefix *string `json:"sourcePrefix,omitempty" tf:"source_prefix,omitempty"`
}

type InventoryMetadataInitParameters struct {
}

type InventoryMetadataObservation struct {
}

type InventoryMetadataParameters struct {
}

type InventoryObservation struct {

	// :
	//
	// Timestamp indicating when the resource was created.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// ID of the destination bucket.
	DestinationBucketID *string `json:"destinationBucketId,omitempty" tf:"destination_bucket_id,omitempty"`

	// Prefix under which bucket inventory will be stored in the destination bucket.
	DestinationPrefix *string `json:"destinationPrefix,omitempty" tf:"destination_prefix,omitempty"`

	// Enable or disable inventory generation.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Labels associated with the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Effective labels sent to the API after merging provider `default_labels` with resource `labels`.
	// +mapType=granular
	LabelsAll map[string]*string `json:"labelsAll,omitempty" tf:"labels_all,omitempty"`

	Metadata *InventoryMetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Include noncurrent versions in inventory if set to true.
	NoncurrentVersions *bool `json:"noncurrentVersions,omitempty" tf:"noncurrent_versions,omitempty"`

	// :
	//
	// Optional fields to include in inventory.
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `OPTIONAL_FIELD_UNSPECIFIED`
	// - `LAST_ACCESS` - Timestamp of the last access.
	// - `CHECKSUM_ALGORITHMS` - Checksum algorithms used.
	// - `INTELLIGENT_TIER` - Current intelligent tier (for Intelligent Storage Class).
	// - `IS_MULTIPART_UPLOAD` - True for multipart uploads, false for simple objects.
	// - `LIFECYCLE_EXPIRATION` - Timestamp of lifecycle expiration.
	// - `TAGS` - Object tags.
	OptionalFields []*string `json:"optionalFields,omitempty" tf:"optional_fields,omitempty"`

	// :
	//
	// Inventory format.
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `OUTPUT_FORMAT_UNSPECIFIED`
	// - `CSV_GZIP` - CSV compressed with GZIP.
	// - `PARQUET_SNAPPY` - Parquet compressed with Snappy.
	OutputFormat *string `json:"outputFormat,omitempty" tf:"output_format,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// :
	//
	// Version of the resource for safe concurrent modifications and consistent reads.
	// Positive and monotonically increases on each resource spec change (but *not* on each change of the
	// resource's container(s) or status).
	// Service allows zero value or current.
	ResourceVersion *float64 `json:"resourceVersion,omitempty" tf:"resource_version,omitempty"`

	// :
	//
	// How often to generate the inventory.
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `SCHEDULE_UNSPECIFIED`
	// - `DAILY` - Run once a day.
	// - `WEEKLY` - Run once a week.
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`

	// Prefix to filter objects in the source bucket.
	SourcePrefix *string `json:"sourcePrefix,omitempty" tf:"source_prefix,omitempty"`

	Status *InventoryStatusObservation `json:"status,omitempty" tf:"status,omitempty"`

	// :
	//
	// Timestamp indicating when the resource was last updated.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type InventoryParameters struct {

	// ID of the destination bucket.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/namespaced/storage/v1beta1.Bucket
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	// +kubebuilder:validation:Optional
	DestinationBucketID *string `json:"destinationBucketId,omitempty" tf:"destination_bucket_id,omitempty"`

	// Reference to a Bucket in storage to populate destinationBucketId.
	// +kubebuilder:validation:Optional
	DestinationBucketIDRef *v2.NamespacedReference `json:"destinationBucketIdRef,omitempty" tf:"-"`

	// Selector for a Bucket in storage to populate destinationBucketId.
	// +kubebuilder:validation:Optional
	DestinationBucketIDSelector *v2.NamespacedSelector `json:"destinationBucketIdSelector,omitempty" tf:"-"`

	// Prefix under which bucket inventory will be stored in the destination bucket.
	// +kubebuilder:validation:Optional
	DestinationPrefix *string `json:"destinationPrefix,omitempty" tf:"destination_prefix,omitempty"`

	// Enable or disable inventory generation.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Labels associated with the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// +kubebuilder:validation:Optional
	Metadata *InventoryMetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Human readable name for the resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Include noncurrent versions in inventory if set to true.
	// +kubebuilder:validation:Optional
	NoncurrentVersions *bool `json:"noncurrentVersions,omitempty" tf:"noncurrent_versions,omitempty"`

	// :
	//
	// Optional fields to include in inventory.
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `OPTIONAL_FIELD_UNSPECIFIED`
	// - `LAST_ACCESS` - Timestamp of the last access.
	// - `CHECKSUM_ALGORITHMS` - Checksum algorithms used.
	// - `INTELLIGENT_TIER` - Current intelligent tier (for Intelligent Storage Class).
	// - `IS_MULTIPART_UPLOAD` - True for multipart uploads, false for simple objects.
	// - `LIFECYCLE_EXPIRATION` - Timestamp of lifecycle expiration.
	// - `TAGS` - Object tags.
	// +kubebuilder:validation:Optional
	OptionalFields []*string `json:"optionalFields,omitempty" tf:"optional_fields,omitempty"`

	// :
	//
	// Inventory format.
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `OUTPUT_FORMAT_UNSPECIFIED`
	// - `CSV_GZIP` - CSV compressed with GZIP.
	// - `PARQUET_SNAPPY` - Parquet compressed with Snappy.
	// +kubebuilder:validation:Optional
	OutputFormat *string `json:"outputFormat,omitempty" tf:"output_format,omitempty"`

	// Identifier of the parent resource to which the resource belongs.
	// +crossplane:generate:reference:type=github.com/upbound/provider-nebius/apis/namespaced/storage/v1beta1.Bucket
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id",true)
	// +kubebuilder:validation:Optional
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// Reference to a Bucket in storage to populate parentId.
	// +kubebuilder:validation:Optional
	ParentIDRef *v2.NamespacedReference `json:"parentIdRef,omitempty" tf:"-"`

	// Selector for a Bucket in storage to populate parentId.
	// +kubebuilder:validation:Optional
	ParentIDSelector *v2.NamespacedSelector `json:"parentIdSelector,omitempty" tf:"-"`

	// :
	//
	// How often to generate the inventory.
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `SCHEDULE_UNSPECIFIED`
	// - `DAILY` - Run once a day.
	// - `WEEKLY` - Run once a week.
	// +kubebuilder:validation:Optional
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`

	// Prefix to filter objects in the source bucket.
	// +kubebuilder:validation:Optional
	SourcePrefix *string `json:"sourcePrefix,omitempty" tf:"source_prefix,omitempty"`
}

type InventoryStatusInitParameters struct {
}

type InventoryStatusObservation struct {

	// :
	//
	// Error code, if the last run was not successful, otherwise NO_ERROR.
	//
	// #### Supported values
	//
	// Possible values:
	//
	// - `NO_ERROR` - No error.
	// - `DESTINATION_BUCKET_NOT_FOUND` - Destination bucket not found.
	// - `PERMISSION_DENIED` - Permission denied: you don't have permission to the destination bucket.
	// - `INVALID_INTENT` - Intent is invalid, does not exist or expired.
	// - `QUOTA_EXCEEDED` - Quota exceeded in destination.
	ErrorCode *string `json:"errorCode,omitempty" tf:"error_code,omitempty"`

	// :
	//
	// Timestamp of the last successful run.
	//
	// A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
	LastSuccess *string `json:"lastSuccess,omitempty" tf:"last_success,omitempty"`
}

type InventoryStatusParameters struct {
}

// InventorySpec defines the desired state of Inventory
type InventorySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            InventoryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InventoryInitParameters `json:"initProvider,omitempty"`
}

// InventoryStatus defines the observed state of Inventory.
type InventoryStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               InventoryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Inventory is the Schema for the Inventorys API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,nebius}
type Inventory struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.outputFormat) || (has(self.initProvider) && has(self.initProvider.outputFormat))",message="spec.forProvider.outputFormat is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.schedule) || (has(self.initProvider) && has(self.initProvider.schedule))",message="spec.forProvider.schedule is a required parameter"
	Spec   InventorySpec   `json:"spec"`
	Status InventoryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InventoryList contains a list of Inventorys
type InventoryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Inventory `json:"items"`
}

// Repository type metadata.
var (
	Inventory_Kind             = "Inventory"
	Inventory_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Inventory_Kind}.String()
	Inventory_KindAPIVersion   = Inventory_Kind + "." + CRDGroupVersion.String()
	Inventory_GroupVersionKind = CRDGroupVersion.WithKind(Inventory_Kind)
)

func init() {
	SchemeBuilder.Register(&Inventory{}, &InventoryList{})
}
